# Generated by Django 5.2.9 on 2026-01-13 02:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
import totem.blog.models
import totem.utils.md
import totem.utils.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('blog', '0001_initial'), ('blog', '0002_blogpost_author'), ('blog', '0003_blogpost_subtitle'), ('blog', '0004_blogpost_publish_alter_blogpost_content'), ('blog', '0005_alter_blogpost_date_published_and_more'), ('blog', '0006_alter_blogpost_header_image'), ('blog', '0007_alter_blogpost_header_image'), ('blog', '0008_alter_blogpost_content'), ('blog', '0009_alter_blogpost_content'), ('blog', '0010_blogpost_read_time'), ('blog', '0011_blogpost_summary'), ('blog', '0012_alter_blogpost_summary')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, default=totem.utils.models.make_slug, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('header_image', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Image for the blog header, must be under 5mb', upload_to=totem.blog.models.upload_to_id_image)),
                ('content', totem.utils.md.MarkdownField(help_text='Markdown content for the blog post. Do not use h1 (single #) headers.\n        Add inline images like {% image slug="vji504tvi" %}, after uploading them in the Images section.', max_length=20000, validators=[totem.utils.md.MarkdownMixin.validate_markdown, django.core.validators.MaxLengthValidator(20000)])),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(help_text='Author of the blog post', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('subtitle', models.CharField(blank=True, max_length=2000)),
                ('publish', models.BooleanField(default=False)),
                ('read_time', models.PositiveIntegerField(default=1, help_text='Estimated reading time in minutes (auto-calculated)')),
                ('summary', models.CharField(blank=True, help_text='Short summary of the blog post to show in list pages. No Markdown allowed. Max 2000 characters.', max_length=2000)),
            ],
            options={
                'ordering': ['-date_published'],
            },
            bases=(totem.utils.models.AdminURLMixin, totem.utils.md.MarkdownMixin, models.Model),
        ),
    ]
