# Generated by Django 5.1.5 on 2025-01-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
