# Generated by Django 5.1.5 on 2025-01-26 03:06

import django.core.validators
import totem.utils.md
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=totem.utils.md.MarkdownField(help_text='Markdown content for the blog post. Do not use h1 (single #) headers.', max_length=10000, validators=[totem.utils.md.MarkdownMixin.validate_markdown, django.core.validators.MaxLengthValidator(10000)]),
        ),
    ]
