# Generated by Django 5.1.5 on 2025-01-26 04:12

import imagekit.models.fields
import totem.blog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogpost_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='header_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Image for the blog header, must be under 5mb', upload_to=totem.blog.models.upload_to_id_image),
        ),
    ]
