# Generated by Django 5.1.5 on 2025-01-26 04:46

import django.core.validators
import totem.utils.md
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpost_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=totem.utils.md.MarkdownField(help_text='Markdown content for the blog post. Do not use h1 (single #) headers.\n        Add inline images like {% image slug="vji504tvi" %}, after uploading them in the Images section.', max_length=10000, validators=[totem.utils.md.MarkdownMixin.validate_markdown, django.core.validators.MaxLengthValidator(10000)]),
        ),
    ]
