# Generated by Django 5.2.5 on 2025-08-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='read_time',
            field=models.PositiveIntegerField(default=1, help_text='Estimated reading time in minutes (auto-calculated)'),
        ),
    ]
