# Generated by Django 5.2.5 on 2025-09-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blogpost_read_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='summary',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
