# Generated by Django 5.2.5 on 2025-09-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogpost_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='summary',
            field=models.CharField(blank=True, help_text='Short summary of the blog post to show in list pages. No Markdown allowed. Max 2000 characters.', max_length=2000),
        ),
    ]
