# Generated by Django 5.2.4 on 2025-08-14 15:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
import taggit.managers
import totem.series.models
import totem.utils.md
import totem.utils.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=2000)),
            ],
            options={
                'verbose_name': 'Series Category',
                'verbose_name_plural': 'Series Categories',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, default=totem.utils.models.make_slug, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=2000)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Image for the Series header, must be under 5mb.', null=True, upload_to=totem.series.models.upload_to_series_image)),
                ('short_description', models.CharField(blank=True, help_text='Short description, max 255 characters.', max_length=255)),
                ('content', totem.utils.md.MarkdownField(default='', help_text='Detailed description of the series.', max_length=10000, validators=[totem.utils.md.MarkdownMixin.validate_markdown, django.core.validators.MaxLengthValidator(10000)])),
                ('published', models.BooleanField(default=False, help_text='Make this series visible to users.')),
                ('author', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='created_series', to=settings.AUTH_USER_MODEL)),
                ('subscribers', models.ManyToManyField(blank=True, related_name='subscribed_series', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('categories', models.ManyToManyField(blank=True, to='series.seriescategory')),
            ],
            options={
                'abstract': False,
            },
            bases=(totem.utils.models.AdminURLMixin, totem.utils.md.MarkdownMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SeriesEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, default=totem.utils.models.make_slug, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='Minutes')),
                ('order', models.PositiveIntegerField(default=1, help_text='The sequence number of this event within the series.')),
                ('published', models.BooleanField(default=False, help_text='Make this event visible.')),
                ('cancelled', models.BooleanField(default=False, help_text='Mark this event as cancelled.')),
                ('meeting_url', models.CharField(blank=True, max_length=255)),
                ('attendees', models.ManyToManyField(blank=True, related_name='events_attending_series', to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='series.series')),
            ],
            options={
                'verbose_name': 'Series Event',
                'verbose_name_plural': 'Series Events',
                'ordering': ['series', 'order', 'start'],
                'unique_together': {('series', 'order'), ('series', 'start', 'title')},
            },
            bases=(totem.utils.models.AdminURLMixin, totem.utils.md.MarkdownMixin, models.Model),
        ),
    ]
