# Generated by Django 4.1.8 on 2023-05-22 22:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WaitList",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("email", models.EmailField(db_index=True, max_length=254, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("subscribed", models.BooleanField(default=False)),
            ],
        ),
    ]
