# Generated by Django 5.2.9 on 2026-01-13 02:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('email', '0001_initial'), ('email', '0002_waitlist_name'), ('email', '0003_alter_waitlist_email_alter_waitlist_name'), ('email', '0004_subscribedmodel_delete_waitlist'), ('email', '0005_emaillog'), ('email', '0006_remove_emaillog_body_remove_emaillog_subscribed_and_more'), ('email', '0007_emailactivity'), ('email', '0008_rename_message_id_emailactivity_activity_id_and_more'), ('email', '0009_emailactivity_date_created_and_more')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscribed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscribed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('context', models.JSONField(null=True)),
                ('recipient', models.CharField(max_length=255)),
                ('template', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Email Logs',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='EmailActivity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('activity_id', models.CharField(max_length=255, unique=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('event_type', models.CharField(max_length=50, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
