# Generated by Django 4.1.9 on 2023-05-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("email", "0002_waitlist_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waitlist",
            name="email",
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name="Your email"),
        ),
        migrations.AlterField(
            model_name="waitlist",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Your name"),
        ),
    ]
