# Generated by Django 4.2.4 on 2023-09-08 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("email", "0004_subscribedmodel_delete_waitlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "subscribed",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="email.subscribedmodel"),
                ),
            ],
            options={
                "verbose_name_plural": "Email Logs",
                "ordering": ("-created",),
            },
        ),
    ]
