# Generated by Django 4.2.9 on 2024-01-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("email", "0005_emaillog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emaillog",
            name="body",
        ),
        migrations.RemoveField(
            model_name="emaillog",
            name="subscribed",
        ),
        migrations.AddField(
            model_name="emaillog",
            name="context",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="emaillog",
            name="recipient",
            field=models.CharField(default="none", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emaillog",
            name="template",
            field=models.CharField(default="none", max_length=255),
            preserve_default=False,
        ),
    ]
