# Generated by Django 5.1.4 on 2024-12-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0006_remove_emaillog_body_remove_emaillog_subscribed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
