# Generated by Django 5.1.4 on 2024-12-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0007_emailactivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailactivity',
            old_name='message_id',
            new_name='activity_id',
        ),
        migrations.RenameField(
            model_name='emailactivity',
            old_name='metadata',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='emailactivity',
            name='event',
        ),
        migrations.AddField(
            model_name='emailactivity',
            name='event_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='emailactivity',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emailactivity',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='emailactivity',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emailactivity',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
