# Generated by Django 5.1.4 on 2024-12-15 21:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0008_rename_message_id_emailactivity_activity_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailactivity',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailactivity',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
