# Generated by Django 5.2.9 on 2026-01-13 02:04

import totem.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('pages', '0004_initial'), ('pages', '0005_alter_redirect_slug'), ('pages', '0006_alter_redirect_slug'), ('pages', '0007_redirect_alternate_slug_and_more'), ('pages', '0008_remove_redirect_unique_redirect_url_and_more'), ('pages', '0009_alter_redirect_slug'), ('pages', '0010_alter_redirect_slug'), ('pages', '0011_alter_redirect_permanent')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, default=totem.utils.models.make_slug, editable=False, unique=True)),
                ('url', models.CharField()),
                ('permanent', models.BooleanField(default=False, help_text='If true, this redirect will be permanent and changes to the URL will work if the user scans the code again.')),
                ('notes', models.TextField(blank=True)),
                ('count', models.BigIntegerField(default=0)),
                ('alternate_slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Redirect',
                'verbose_name_plural': 'Redirects',
                'ordering': ['url'],
                'indexes': [models.Index(fields=['url'], name='pages_redir_url_96914e_idx')],
                'constraints': [],
            },
        ),
    ]
