# Generated by Django 4.2.5 on 2023-09-18 01:09

from django.db import migrations, models
import totem.utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0005_alter_redirect_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redirect",
            name="slug",
            field=models.SlugField(blank=True, default=totem.utils.models.make_slug, editable=False, unique=True),
        ),
    ]
