# Generated by Django 4.2.5 on 2023-09-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0006_alter_redirect_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="redirect",
            name="alternate_slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name="redirect",
            constraint=models.UniqueConstraint(fields=("alternate_slug",), name="unique_redirect_alternate_slug"),
        ),
    ]
