# Generated by Django 5.0.2 on 2024-02-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_redirect_unique_redirect_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, unique=True),
        ),
    ]
