version: "3"

volumes:
  totem_local_postgres_data: {}
  totem_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: totem_local_django
    container_name: totem_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.env
    ports:
      - "8000:8000"
    command: /start
    labels:
      - dev.orbstack.domains=totem.local

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    image: totem_production_postgres
    container_name: totem_local_postgres
    volumes:
      - totem_local_postgres_data:/var/lib/postgresql/data
      - totem_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: always
    volumes:
      - ./.mailpit:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
