# Generated by Django 4.1.8 on 2023-04-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0002_circleplan_date_modified_circleplan_display_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="circleplan",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
