import uuid
from typing import TYPE_CHECKING

from django.conf import settings
from django.db import models

if TYPE_CHECKING:
    pass


class ChatRoom(models.Model):
    """
    Represents a conversational channel. Can be direct (1-to-1),
    group-based, or tightly bound to a Totem Session.
    """

    class RoomType(models.TextChoices):
        DIRECT = "direct", "Direct Message"
        GROUP = "group", "Group Chat"
        SESSION = "session", "Session Chat"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    room_type = models.CharField(max_length=15, choices=RoomType.choices, default=RoomType.DIRECT)
    session = models.ForeignKey(
        "spaces.Session",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="chat_rooms",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "chat_rooms"
        indexes = [
            models.Index(fields=["session_id"]),
        ]

    def __str__(self) -> str:
        return f"<ChatRoom: {self.id} ({self.room_type})>"


class ChatParticipant(models.Model):
    """
    Intersection table managing membership of users within ChatRooms.
    Optimizes unread badges and localized read-tracking.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    room = models.ForeignKey(ChatRoom, on_delete=models.CASCADE, related_name="participants")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="chat_memberships")
    joined_at = models.DateTimeField(auto_now_add=True)
    last_read_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "chat_participants"
        unique_together = ("room", "user")
        indexes = [
            models.Index(fields=["user_id", "last_read_at"]),
        ]

    def __str__(self) -> str:
        return f"<ChatParticipant: {self.user_id} in {self.room_id}>"


class ChatMessage(models.Model):
    """
    The transactional message table. Designed for fast cursor-based slicing.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    room = models.ForeignKey(ChatRoom, on_delete=models.CASCADE, related_name="messages")
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="sent_messages")
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    client_id = models.UUIDField(
        unique=True,
        null=True,
        blank=True,
        help_text="UUID generated by the client to achieve exact idempotency and optimistic UI deduplication.",
    )
    session = models.ForeignKey(
        "spaces.Session",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="session_messages",
        help_text="Explicit session assignment for keeper-initiated bulk messaging.",
    )

    class Meta:
        db_table = "chat_messages"
        ordering = ("-created_at",)
        indexes = [
            models.Index(fields=["room_id", "-created_at", "-id"], name="chat_msg_room_created_id_idx"),
            models.Index(fields=["session_id"]),
        ]

    def __str__(self) -> str:
        return f"<ChatMessage: {self.id} in {self.room_id}>"

    @property
    def sender_name(self) -> str:
        return self.sender.name or self.sender.email
