# Generated by Django 4.1.8 on 2023-04-28 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="circleplan",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="circleplan",
            name="display_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
