# Generated by Django 4.2.6 on 2023-10-20 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0003_circleplan_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circleplan",
            name="content",
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(10000)]),
        ),
        migrations.AlterField(
            model_name="circleplan",
            name="description",
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
    ]
