# Generated by Django 5.2.9 on 2026-01-13 02:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
import taggit.managers
import totem.circles.models
import totem.utils.fields
import totem.utils.md
import totem.utils.models
from django.conf import settings
from django.db import migrations, models


# Data migrations from the original migrations are no-ops for fresh installs
# since there's no existing data to migrate.


class Migration(migrations.Migration):

    replaces = [('circles', '0001_initial'), ('circles', '0002_alter_circle_author'), ('circles', '0003_rename_starts_circle_start'), ('circles', '0004_circle_attendees'), ('circles', '0005_alter_circle_image_url'), ('circles', '0006_remove_circle_image_url'), ('circles', '0007_circle_open'), ('circles', '0008_alter_circle_open_alter_circle_published'), ('circles', '0009_remove_circle_description_circle_content'), ('circles', '0010_alter_circle_slug'), ('circles', '0011_circle_rrule'), ('circles', '0012_rename_rrule_circle_rrulestr'), ('circles', '0013_remove_circle_attendees_remove_circle_google_url_and_more'), ('circles', '0014_circleevent_cancelled'), ('circles', '0015_alter_circle_price'), ('circles', '0016_alter_circleevent_start'), ('circles', '0017_circle_image'), ('circles', '0018_remove_circle_duration'), ('circles', '0019_circleevent_joined_circleevent_meeting_url_and_more'), ('circles', '0020_circleevent_advertised_circleevent_notified'), ('circles', '0021_alter_circle_slug_alter_circleevent_slug'), ('circles', '0022_alter_circle_slug_alter_circleevent_slug'), ('circles', '0023_alter_circle_image_alter_circle_recurring'), ('circles', '0024_alter_circle_image'), ('circles', '0025_alter_circle_image'), ('circles', '0026_alter_circle_author'), ('circles', '0027_alter_circle_content'), ('circles', '0028_alter_circle_recurring'), ('circles', '0029_circleevent_listed'), ('circles', '0030_circleevent_notified_tomorrow'), ('circles', '0031_circlecategory_circleevent_content_alter_circle_tags_and_more'), ('circles', '0032_alter_circlecategory_options_alter_circle_content_and_more'), ('circles', '0033_alter_circle_content_alter_circleevent_content'), ('circles', '0034_alter_circleevent_content'), ('circles', '0035_alter_circle_slug_alter_circleevent_slug'), ('circles', '0036_alter_circle_slug_alter_circleevent_slug'), ('circles', '0037_circleevent_title'), ('circles', '0038_alter_circlecategory_options_alter_circle_image_and_more'), ('circles', '0039_alter_circleevent_options_and_more'), ('circles', '0040_alter_circleevent_unique_together'), ('circles', '0041_circleevent_notified_missed'), ('circles', '0042_alter_circleevent_cancelled'), ('circles', '0043_circle_short_description'), ('circles', '0044_circleevent_meeting_provider'), ('circles', '0045_sessionfeedback'), ('circles', '0046_move_meeting_provider_to_circle')]

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CircleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=2000)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=totem.utils.models.make_slug, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=2000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False, help_text='Is this listing visible?')),
                ('recurring', models.CharField(help_text='Example: Once a month (or week, day, etc). Do not put specific times or days of the week.', max_length=255)),
                ('author', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='created_circles', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('open', models.BooleanField(default=True, help_text='Is this listing open for more attendees?')),
                ('content', totem.utils.md.MarkdownField(default='', max_length=10000, validators=[totem.utils.md.MarkdownMixin.validate_markdown, django.core.validators.MaxLengthValidator(10000)])),
                ('subscribed', models.ManyToManyField(blank=True, related_name='subscribed_circles', to=settings.AUTH_USER_MODEL)),
                ('price', models.IntegerField(default=0, help_text='Price in USD dollars. If you want to offer this listing for free, enter 0.', validators=[django.core.validators.MinValueValidator(0, message='Price must be greater than or equal to 0'), django.core.validators.MaxValueValidator(1000, message='Price must be less than or equal to 1000')], verbose_name='Price (USD)')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Image for the Space header, must be under 5mb', null=True, upload_to=totem.circles.models.upload_to_id_image)),
                ('categories', models.ManyToManyField(blank=True, to='circles.circlecategory')),
                ('short_description', models.CharField(blank=True, help_text='Short description, max 255 characters', max_length=255)),
                ('meeting_provider', models.CharField(choices=[('google_meet', 'Google Meet'), ('livekit', 'LiveKit')], default='google_meet', help_text='The video conferencing provider for this circle.', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CircleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=totem.utils.models.make_slug, editable=False, unique=True)),
                ('open', models.BooleanField(default=True, help_text='Is this session open for more attendees?')),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='Minutes')),
                ('seats', models.IntegerField(default=8)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='events_attending', to=settings.AUTH_USER_MODEL)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='circles.circle')),
                ('cancelled', models.BooleanField(default=False, help_text='Is this session canceled?')),
                ('joined', models.ManyToManyField(blank=True, related_name='events_joined', to=settings.AUTH_USER_MODEL)),
                ('meeting_url', models.CharField(blank=True, max_length=255)),
                ('advertised', models.BooleanField(default=False)),
                ('notified', models.BooleanField(default=False)),
                ('listed', models.BooleanField(default=True, help_text='Is this session discoverable? False means events are only accessible via direct link, or to people attending.')),
                ('notified_tomorrow', models.BooleanField(default=False)),
                ('content', totem.utils.md.MarkdownField(blank=True, help_text='Optional description for this specific session. Markdown is supported.', max_length=10000, null=True, validators=[totem.utils.md.MarkdownMixin.validate_markdown, django.core.validators.MaxLengthValidator(10000)])),
                ('title', models.CharField(blank=True, max_length=255)),
                ('notified_missed', models.BooleanField(default=False)),
                ('meeting_provider', models.CharField(choices=[('google_meet', 'Google Meet'), ('livekit', 'LiveKit')], default='google_meet', help_text='The video conferencing provider for this event.', max_length=20)),
            ],
            options={
                'abstract': False,
                'ordering': ['start'],
                'unique_together': {('circle', 'start', 'open', 'title')},
            },
            bases=(totem.utils.md.MarkdownMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SessionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('feedback', models.CharField(choices=[('up', 'Thumbs Up'), ('down', 'Thumbs Down')], max_length=4)),
                ('message', totem.utils.fields.MaxLengthTextField(blank=True, max_length=2000, validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='circles.circleevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('event', 'user'), name='unique_user_feedback_for_event')],
            },
            bases=(totem.utils.models.AdminURLMixin, models.Model),
        ),
        # Original: copy_meeting_provider_to_circle - not needed for fresh install (no existing data)
        migrations.RunPython(
            code=migrations.RunPython.noop,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='circleevent',
            name='meeting_provider',
        ),
    ]
