# Generated by Django 4.2.3 on 2023-07-25 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("taggit", "0005_auto_20220424_2025"),
    ]

    operations = [
        migrations.CreateModel(
            name="Circle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(blank=True, editable=False, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(max_length=2000)),
                ("description", models.TextField()),
                ("image_url", models.URLField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("published", models.BooleanField(default=False)),
                ("price", models.CharField(max_length=255)),
                ("starts", models.DateTimeField()),
                ("duration", models.CharField(max_length=255)),
                ("recurring", models.CharField(max_length=255)),
                ("google_url", models.URLField()),
                (
                    "author",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
