# Generated by Django 4.2.3 on 2023-07-25 04:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("circles", "0002_alter_circle_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="circle",
            old_name="starts",
            new_name="start",
        ),
    ]
