# Generated by Django 4.2.3 on 2023-07-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("circles", "0004_circle_attendees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circle",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
