# Generated by Django 4.2.3 on 2023-07-25 20:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("circles", "0005_alter_circle_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="circle",
            name="image_url",
        ),
    ]
