# Generated by Django 4.2.3 on 2023-07-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("circles", "0006_remove_circle_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="circle",
            name="open",
            field=models.BooleanField(default=True),
        ),
    ]
