# Generated by Django 4.2.3 on 2023-07-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("circles", "0007_circle_open"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circle",
            name="open",
            field=models.BooleanField(default=True, help_text="Is this Circle for more attendees?"),
        ),
        migrations.AlterField(
            model_name="circle",
            name="published",
            field=models.BooleanField(default=False, help_text="Is this Circle visible?"),
        ),
    ]
