# Generated by Django 4.2.3 on 2023-07-31 06:01

from django.db import migrations
import totem.utils.md


class Migration(migrations.Migration):
    dependencies = [
        ("circles", "0008_alter_circle_open_alter_circle_published"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="circle",
            name="description",
        ),
        migrations.AddField(
            model_name="circle",
            name="content",
            field=totem.utils.md.MarkdownField(
                default="", validators=[totem.utils.md.MarkdownMixin.validate_markdown]
            ),
        ),
    ]
