# Generated by Django 4.2.3 on 2023-08-08 21:58

from django.db import migrations, models
import totem.utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("circles", "0009_remove_circle_description_circle_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circle",
            name="slug",
            field=models.SlugField(blank=True, default=totem.utils.models.make_slug, editable=False, unique=True),
        ),
    ]
