# Generated by Django 4.2.4 on 2023-08-24 06:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("circles", "0011_circle_rrule"),
    ]

    operations = [
        migrations.RenameField(
            model_name="circle",
            old_name="rrule",
            new_name="rrulestr",
        ),
    ]
