# Generated by Django 4.2.4 on 2023-08-24 21:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import totem.utils.md
import totem.utils.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("circles", "0012_rename_rrule_circle_rrulestr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="circle",
            name="attendees",
        ),
        migrations.RemoveField(
            model_name="circle",
            name="google_url",
        ),
        migrations.RemoveField(
            model_name="circle",
            name="rrulestr",
        ),
        migrations.RemoveField(
            model_name="circle",
            name="start",
        ),
        migrations.AddField(
            model_name="circle",
            name="subscribed",
            field=models.ManyToManyField(blank=True, related_name="subscribed_circles", to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name="circle",
            name="price",
        ),
        migrations.AddField(
            model_name="circle",
            name="price",
            field=models.IntegerField(
                default=0,
                help_text="Price in USD dollars",
                validators=[
                    django.core.validators.MinValueValidator(0, message="Price must be greater than or equal to 0"),
                    django.core.validators.MaxValueValidator(1000, message="Price must be less than or equal to 100"),
                ],
                verbose_name="Price (USD)",
            ),
        ),
        migrations.CreateModel(
            name="CircleEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "slug",
                    models.SlugField(blank=True, default=totem.utils.models.make_slug, editable=False, unique=True),
                ),
                ("open", models.BooleanField(default=True, help_text="Is this Circle for more attendees?")),
                ("start", models.DateTimeField()),
                ("duration_minutes", models.IntegerField(default=60, verbose_name="Minutes")),
                ("seats", models.IntegerField(default=8)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "attendees",
                    models.ManyToManyField(blank=True, related_name="attending", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="events", to="circles.circle"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(totem.utils.md.MarkdownMixin, models.Model),
        ),
    ]
