# Generated by Django 4.2.4 on 2023-08-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("circles", "0013_remove_circle_attendees_remove_circle_google_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="circleevent",
            name="cancelled",
            field=models.BooleanField(default=False, help_text="Is this Circle cancelled?"),
        ),
    ]
