# Generated by Django 4.2.4 on 2023-08-25 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("circles", "0015_alter_circle_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circleevent",
            name="start",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
