# Generated by Django 4.2.4 on 2023-09-01 06:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("circles", "0017_circle_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="circle",
            name="duration",
        ),
    ]
