# Generated by Django 4.2.5 on 2023-09-18 01:09

from django.db import migrations, models
import totem.utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("circles", "0021_alter_circle_slug_alter_circleevent_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circle",
            name="slug",
            field=models.SlugField(blank=True, default=totem.utils.models.make_slug, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="circleevent",
            name="slug",
            field=models.SlugField(blank=True, default=totem.utils.models.make_slug, editable=False, unique=True),
        ),
    ]
