# Generated by Django 4.2.5 on 2023-09-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("circles", "0022_alter_circle_slug_alter_circleevent_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circle",
            name="image",
            field=models.ImageField(
                blank=True, help_text="Image for the Circle, must be under 5mb", null=True, upload_to="circles"
            ),
        ),
        migrations.AlterField(
            model_name="circle",
            name="recurring",
            field=models.CharField(help_text="Example: Every Tuesday at 5pm", max_length=255),
        ),
    ]
