# Generated by Django 4.2.5 on 2023-09-28 23:33

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("circles", "0023_alter_circle_image_alter_circle_recurring"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circle",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, help_text="Image for the Circle, must be under 5mb", null=True, upload_to="circles"
            ),
        ),
    ]
