# Generated by Django 4.2.7 on 2023-11-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("circles", "0027_alter_circle_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circle",
            name="recurring",
            field=models.CharField(
                help_text="Example: Once a month (or week, day, etc). Do not put specific times or days of the week.",
                max_length=255,
            ),
        ),
    ]
