# Generated by Django 4.2.7 on 2023-11-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("circles", "0028_alter_circle_recurring"),
    ]

    operations = [
        migrations.AddField(
            model_name="circleevent",
            name="listed",
            field=models.BooleanField(
                default=True,
                help_text="Is this Circle discoverable? False means events are only accessible via direct link, or to people attending.",
            ),
        ),
    ]
