# Generated by Django 4.2.9 on 2024-01-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("circles", "0029_circleevent_listed"),
    ]

    operations = [
        migrations.AddField(
            model_name="circleevent",
            name="notified_tomorrow",
            field=models.BooleanField(default=False),
        ),
    ]
