# Generated by Django 5.0.1 on 2024-01-27 02:10

import django.core.validators
import taggit.managers
import totem.utils.md
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("circles", "0030_circleevent_notified_tomorrow"),
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="CircleCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.CharField(blank=True, max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name="circleevent",
            name="content",
            field=totem.utils.md.MarkdownField(
                default="",
                help_text="Optional description for this specific Circle session. Markdown is supported.",
                max_length=10000,
                validators=[
                    totem.utils.md.MarkdownMixin.validate_markdown,
                    django.core.validators.MaxLengthValidator(10000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="circle",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="circle",
            name="categories",
            field=models.ManyToManyField(blank=True, to="circles.circlecategory"),
        ),
    ]
