# Generated by Django 5.0.1 on 2024-01-30 22:13

import django.core.validators
import totem.utils.md
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("circles", "0031_circlecategory_circleevent_content_alter_circle_tags_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="circlecategory",
            options={"verbose_name_plural": "circle categories"},
        ),
        migrations.AlterField(
            model_name="circle",
            name="content",
            field=totem.utils.md.MarkdownField(
                default="",
                max_length=500,
                validators=[
                    totem.utils.md.MarkdownMixin.validate_markdown,
                    django.core.validators.MaxLengthValidator(500),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="circleevent",
            name="content",
            field=totem.utils.md.MarkdownField(
                help_text="Optional description for this specific Circle session. Markdown is supported.",
                max_length=500,
                null=True,
                validators=[
                    totem.utils.md.MarkdownMixin.validate_markdown,
                    django.core.validators.MaxLengthValidator(500),
                ],
            ),
        ),
    ]
