# Generated by Django 5.0.1 on 2024-01-30 22:16

import django.core.validators
import totem.utils.md
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("circles", "0032_alter_circlecategory_options_alter_circle_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circle",
            name="content",
            field=totem.utils.md.MarkdownField(
                default="",
                max_length=10000,
                validators=[
                    totem.utils.md.MarkdownMixin.validate_markdown,
                    django.core.validators.MaxLengthValidator(10000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="circleevent",
            name="content",
            field=totem.utils.md.MarkdownField(
                help_text="Optional description for this specific Circle session. Markdown is supported.",
                max_length=10000,
                null=True,
                validators=[
                    totem.utils.md.MarkdownMixin.validate_markdown,
                    django.core.validators.MaxLengthValidator(10000),
                ],
            ),
        ),
    ]
