# Generated by Django 5.0.2 on 2024-02-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0034_alter_circleevent_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='circleevent',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, unique=True),
        ),
    ]
