# Generated by Django 5.0.2 on 2024-02-13 21:51

import totem.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0035_alter_circle_slug_alter_circleevent_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='slug',
            field=models.SlugField(blank=True, default=totem.utils.models.make_slug, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='circleevent',
            name='slug',
            field=models.SlugField(blank=True, default=totem.utils.models.make_slug, editable=False, unique=True),
        ),
    ]
