# Generated by Django 5.0.4 on 2024-05-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0036_alter_circle_slug_alter_circleevent_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='circleevent',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
