# Generated by Django 5.0.7 on 2024-08-03 00:23

import django.core.validators
import imagekit.models.fields
import totem.circles.models
import totem.utils.md
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0037_circleevent_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circlecategory',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='circle',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Image for the Space header, must be under 5mb', null=True, upload_to=totem.circles.models.upload_to_id_image),
        ),
        migrations.AlterField(
            model_name='circle',
            name='open',
            field=models.BooleanField(default=True, help_text='Is this listing open for more attendees?'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='price',
            field=models.IntegerField(default=0, help_text='Price in USD dollars. If you want to offer this listing for free, enter 0.', validators=[django.core.validators.MinValueValidator(0, message='Price must be greater than or equal to 0'), django.core.validators.MaxValueValidator(1000, message='Price must be less than or equal to 1000')], verbose_name='Price (USD)'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='published',
            field=models.BooleanField(default=False, help_text='Is this listing visible?'),
        ),
        migrations.AlterField(
            model_name='circleevent',
            name='cancelled',
            field=models.BooleanField(default=False, help_text='Is this session cancelled?'),
        ),
        migrations.AlterField(
            model_name='circleevent',
            name='content',
            field=totem.utils.md.MarkdownField(blank=True, help_text='Optional description for this specific session. Markdown is supported.', max_length=10000, null=True, validators=[totem.utils.md.MarkdownMixin.validate_markdown, django.core.validators.MaxLengthValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='circleevent',
            name='listed',
            field=models.BooleanField(default=True, help_text='Is this session discoverable? False means events are only accessible via direct link, or to people attending.'),
        ),
        migrations.AlterField(
            model_name='circleevent',
            name='open',
            field=models.BooleanField(default=True, help_text='Is this session open for more attendees?'),
        ),
    ]
