# Generated by Django 5.0.8 on 2024-08-11 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0038_alter_circlecategory_options_alter_circle_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circleevent',
            options={'ordering': ['start']},
        ),
        migrations.AlterUniqueTogether(
            name='circleevent',
            unique_together={('circle', 'start', 'open')},
        ),
    ]
