# Generated by Django 5.0.8 on 2024-08-11 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0039_alter_circleevent_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='circleevent',
            unique_together={('circle', 'start', 'open', 'title')},
        ),
    ]
