# Generated by Django 5.0.8 on 2024-08-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0040_alter_circleevent_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='circleevent',
            name='notified_missed',
            field=models.BooleanField(default=False),
        ),
    ]
