# Generated by Django 5.1.5 on 2025-01-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0041_circleevent_notified_missed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circleevent',
            name='cancelled',
            field=models.BooleanField(default=False, help_text='Is this session canceled?'),
        ),
    ]
