# Generated by Django 5.2.6 on 2025-09-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0043_circle_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='circleevent',
            name='meeting_provider',
            field=models.CharField(choices=[('livekit', 'LiveKit'), ('google_meet', 'Google Meet')], default='google_meet', help_text='The video conferencing provider for this event.', max_length=20),
        ),
    ]
