# Generated by Django 5.2.7 on 2025-12-18 03:34

import django.core.validators
import django.db.models.deletion
import totem.utils.fields
import totem.utils.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0044_circleevent_meeting_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('feedback', models.CharField(choices=[('up', 'Thumbs Up'), ('down', 'Thumbs Down')], max_length=4)),
                ('message', totem.utils.fields.MaxLengthTextField(blank=True, max_length=2000, validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='circles.circleevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('event', 'user')},
            },
            bases=(totem.utils.models.AdminURLMixin, models.Model),
        ),
    ]
