# Generated by Django 5.2.9 on 2026-01-13 02:04

import imagekit.models.fields
import totem.uploads.models
import totem.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Image for content, must be under 5mb', null=True, upload_to=totem.uploads.models.upload_to_id_image)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, default=totem.utils.models.make_slug, editable=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
