# Generated by Django 5.1.5 on 2025-01-26 04:23

import imagekit.models.fields
import totem.uploads.models
import totem.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='slug',
            field=models.SlugField(blank=True, default=totem.utils.models.make_slug, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Image for content, must be under 5mb', null=True, upload_to=totem.uploads.models.upload_to_id_image),
        ),
    ]
