# Generated by Django 5.2.9 on 2026-01-13 02:04

import django.core.validators
import django.db.models.deletion
import totem.utils.md
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('course', '0001_initial'), ('course', '0002_alter_course_content'), ('course', '0003_circlescript'), ('course', '0004_coursepage'), ('course', '0005_delete_circlescript_coursepage_created_by_and_more'), ('course', '0006_alter_coursepage_content'), ('course', '0007_alter_coursepage_content'), ('course', '0008_alter_coursepage_content')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('enable_toc', models.BooleanField(default=False)),
                ('content', totem.utils.md.MarkdownField(max_length=1000000, validators=[totem.utils.md.MarkdownMixin.validate_markdown, django.core.validators.MaxLengthValidator(1000000)])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(totem.utils.md.MarkdownMixin, models.Model),
        ),
    ]
