# Generated by Django 4.1.8 on 2023-05-13 07:19

from django.db import migrations
import totem.utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="content",
            field=totem.utils.fields.MarkdownField(),
        ),
    ]
