# Generated by Django 4.1.8 on 2023-05-15 20:00

from django.db import migrations, models
import totem.course.models
import totem.utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0002_alter_course_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="CircleScript",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("content", totem.utils.fields.MarkdownField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
            ],
            bases=(totem.course.models.MardownMixin, models.Model),
        ),
    ]
