# Generated by Django 4.1.8 on 2023-05-17 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course", "0004_coursepage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CircleScript",
        ),
        migrations.AddField(
            model_name="coursepage",
            name="created_by",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Course",
        ),
    ]
