# Generated by Django 4.1.8 on 2023-05-18 17:54

from django.db import migrations
import totem.course.models
import totem.utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0005_delete_circlescript_coursepage_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursepage",
            name="content",
            field=totem.utils.fields.MarkdownField(validators=[totem.course.models.MardownMixin.validate_markdown]),
        ),
    ]
