# Generated by Django 4.2.6 on 2023-10-25 18:45

import django.core.validators
from django.db import migrations
import totem.utils.md


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0007_alter_coursepage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursepage",
            name="content",
            field=totem.utils.md.MarkdownField(
                max_length=1000000,
                validators=[
                    totem.utils.md.MarkdownMixin.validate_markdown,
                    django.core.validators.MaxLengthValidator(1000000),
                ],
            ),
        ),
    ]
