# Generated by Django 5.2.9 on 2026-01-13 02:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
import timezone_field.fields
import totem.email.utils
import totem.users.managers
import totem.users.models
import totem.utils.fields
import totem.utils.md
import totem.utils.models
import uuid
from django.conf import settings
from django.db import migrations, models


# Data migrations from the original migrations are no-ops for fresh installs
# since there's no existing data to migrate.


class Migration(migrations.Migration):

    replaces = [('users', '0001_initial'), ('users', '0002_user_api_key'), ('users', '0003_alter_user_email'), ('users', '0004_user_profile_image'), ('users', '0005_user_ics_key'), ('users', '0006_alter_user_profile_image'), ('users', '0007_user_verified_alter_user_name'), ('users', '0008_alter_user_options_user_slug'), ('users', '0009_auto_20230808_2204'), ('users', '0010_auto_20230808_2204'), ('users', '0011_alter_user_slug'), ('users', '0012_user_date_created_user_date_modified'), ('users', '0013_user_timezone'), ('users', '0014_alter_user_timezone'), ('users', '0015_alter_user_slug'), ('users', '0016_alter_user_slug'), ('users', '0017_alter_user_timezone'), ('users', '0018_alter_user_timezone'), ('users', '0019_alter_user_profile_image'), ('users', '0020_alter_user_profile_image'), ('users', '0021_user_profile_avatar_seed_user_profile_avatar_type'), ('users', '0022_keeperprofile'), ('users', '0023_feedback'), ('users', '0024_actiontoken'), ('users', '0025_remove_actiontoken_used_alter_actiontoken_expires_at'), ('users', '0026_alter_keeperprofile_bio'), ('users', '0027_alter_keeperprofile_bio'), ('users', '0028_alter_user_slug'), ('users', '0029_alter_user_slug'), ('users', '0030_keeperprofile_title'), ('users', '0031_alter_keeperprofile_title'), ('users', '0032_keeperprofile_instagram_username_and_more'), ('users', '0033_alter_keeperprofile_instagram_username_and_more'), ('users', '0034_keeperprofile_username'), ('users', '0035_alter_keeperprofile_username'), ('users', '0036_alter_keeperprofile_instagram_username_and_more'), ('users', '0037_user_newsletter_consent'), ('users', '0038_alter_user_newsletter_consent'), ('users', '0039_loginpin'), ('users', '0040_loginpin_users_login_user_id_f0e42f_idx'), ('users', '0041_alter_user_ics_key_refreshtoken'), ('users', '0042_alter_user_api_key'), ('users', '0043_alter_user_timezone'), ('users', '0044_user_fixed_pin_user_fixed_pin_enabled'), ('users', '0045_keeperprofile_bluesky_username'), ('users', '0046_remove_refreshtoken_users_refre_user_id_37e728_idx_and_more')]

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[totem.email.utils.validate_email_blocked], verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('api_key', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='API Key')),
                ('profile_image', models.CharField(blank=True, max_length=255, null=True)),
                ('ics_key', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='API Key')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('slug', models.SlugField(blank=True, default=totem.utils.models.make_slug, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', totem.users.managers.TotemUserManager()),
            ],
        ),
        # Original: gen_uuid - not needed for fresh install (no existing users)
        migrations.RunPython(
            code=migrations.RunPython.noop,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, default=totem.utils.models.make_slug, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, choices_display='WITH_GMT_OFFSET'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Profile image, must be under 5mb. Will be cropped to a square.', null=True, upload_to=totem.users.models.upload_to_id_image),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_avatar_seed',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_avatar_type',
            field=models.CharField(choices=[('TD', 'Tie Dye'), ('IM', 'Image')], default='TD', max_length=2),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('message', totem.utils.fields.MaxLengthTextField(max_length=10000, validators=[django.core.validators.MaxLengthValidator(10000)], verbose_name='Feedback')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(max_length=100)),
                ('parameters', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField(default=totem.users.models.default_expires_at)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='newsletter_consent',
            field=models.BooleanField(default=False, verbose_name='Receive updates from Totem'),
        ),
        migrations.CreateModel(
            name='LoginPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField(default=totem.users.models.default_pin_expires_at)),
                ('used', models.BooleanField(default=False)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'pin', 'expires_at'], name='users_login_user_id_f0e42f_idx')],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='ics_key',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='ICS Key'),
        ),
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='API Key'),
        ),
        migrations.AddField(
            model_name='user',
            name='fixed_pin',
            field=models.CharField(blank=True, default='', help_text='Fixed PIN for app store review access. Must be enabled to work.', max_length=6, verbose_name='Fixed PIN'),
        ),
        migrations.AddField(
            model_name='user',
            name='fixed_pin_enabled',
            field=models.BooleanField(default=False, help_text='Enable fixed PIN login for app store reviews. Not allowed for staff users.', verbose_name='Fixed PIN Enabled'),
        ),
        migrations.CreateModel(
            name='KeeperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', totem.utils.md.MarkdownField(blank=True, max_length=10000, validators=[totem.utils.md.MarkdownMixin.validate_markdown, django.core.validators.MaxLengthValidator(10000)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='keeper_profile', to=settings.AUTH_USER_MODEL)),
                ('title', models.CharField(default='Keeper', max_length=255)),
                ('instagram_username', models.CharField(blank=True, help_text='Your Instagram username, no @ symbol', max_length=255)),
                ('languages', models.CharField(default='English', help_text='What languages do you speak? (English, Spanish, etc.)', max_length=255)),
                ('location', models.CharField(default='Earth', help_text='Where are you located? (City, State, Country)', max_length=255)),
                ('website', models.URLField(blank=True, help_text='Your personal website.', max_length=255)),
                ('x_username', models.CharField(blank=True, help_text='Your X username, no @ symbol', max_length=255)),
                ('username', models.CharField(blank=True, db_index=True, help_text='Your unique username.', max_length=30, null=True, unique=True)),
                ('bluesky_username', models.CharField(blank=True, help_text='Your Bluesky username, no @ symbol', max_length=255)),
            ],
            bases=(models.Model, totem.utils.md.MarkdownMixin),
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [],
            },
        ),
        # Original: clear_refresh_tokens - not needed for fresh install (no existing tokens)
        migrations.RunPython(
            code=migrations.RunPython.noop,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='token_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['user', 'created_at'], name='users_refre_user_id_c102a0_idx'),
        ),
    ]
