# Generated by Django 4.1.9 on 2023-07-04 01:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="api_key",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name="API Key"),
        ),
    ]
