# Generated by Django 6.0.7 on 2026-07-16 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginpin',
            name='used',
        ),
        migrations.AlterField(
            model_name='loginpin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_pins', to=settings.AUTH_USER_MODEL),
        ),
    ]
