# Generated by Django 4.2.3 on 2023-07-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
