# Generated by Django 4.2.3 on 2023-07-25 22:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ics_key",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name="API Key"),
        ),
    ]
