# Generated by Django 4.2.3 on 2023-07-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_ics_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
