# Generated by Django 4.2.3 on 2023-08-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verified",
            field=models.BooleanField(default=False, verbose_name="Verified"),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Name"),
        ),
    ]
