# Generated by Django 4.2.3 on 2023-08-08 21:58

from django.db import migrations, models
import totem.utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_user_verified_alter_user_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddField(
            model_name="user",
            name="slug",
            field=models.SlugField(blank=True, default=totem.utils.models.make_slug, editable=False, null=True),
        ),
    ]
