# Generated by Django 4.2.3 on 2023-08-08 22:04

from django.db import migrations, models
from totem.utils.models import make_slug


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_auto_20230808_2204"),
    ]

    operations = [
        migrations.AlterField(
            model_name="User",
            name="slug",
            field=models.SlugField(default=make_slug, unique=True),
        ),
    ]
