# Generated by Django 4.2.4 on 2023-09-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_user_date_created_user_date_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=models.CharField(default="America/New_York", max_length=255),
        ),
    ]
