# Generated by Django 4.2.5 on 2023-09-18 01:07

from django.db import migrations, models
import totem.utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_alter_user_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="slug",
            field=models.SlugField(blank=True, default=totem.utils.models.make_slug, unique=True),
        ),
    ]
