# Generated by Django 4.2.5 on 2023-09-27 18:30

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_alter_user_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(default="America/Los_Angeles"),
        ),
    ]
