# Generated by Django 4.2.5 on 2023-09-27 18:36

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_alter_user_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(choices_display="WITH_GMT_OFFSET"),
        ),
    ]
