# Generated by Django 4.2.5 on 2023-09-29 19:22

from django.db import migrations
import imagekit.models.fields
import totem.users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_alter_user_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                help_text="Profile image, must be under 5mb",
                null=True,
                upload_to=totem.users.models.upload_to_id_image,
            ),
        ),
    ]
