# Generated by Django 4.2.5 on 2023-10-12 21:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_alter_user_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_avatar_seed",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_avatar_type",
            field=models.CharField(choices=[("TD", "Tie Dye"), ("IM", "Image")], default="TD", max_length=2),
        ),
    ]
