# Generated by Django 4.2.9 on 2024-01-21 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0023_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("action", models.CharField(max_length=100)),
                ("parameters", models.JSONField(default=dict)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
