# Generated by Django 4.2.9 on 2024-01-23 04:42

from django.db import migrations, models
import totem.users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0024_actiontoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actiontoken",
            name="used",
        ),
        migrations.AlterField(
            model_name="actiontoken",
            name="expires_at",
            field=models.DateTimeField(default=totem.users.models.default_expires_at),
        ),
    ]
