# Generated by Django 5.0.1 on 2024-01-30 22:16

import django.core.validators
import totem.utils.md
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0026_alter_keeperprofile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keeperprofile",
            name="bio",
            field=totem.utils.md.MarkdownField(
                blank=True,
                max_length=10000,
                validators=[
                    totem.utils.md.MarkdownMixin.validate_markdown,
                    django.core.validators.MaxLengthValidator(10000),
                ],
            ),
        ),
    ]
