# Generated by Django 5.0.2 on 2024-03-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='keeperprofile',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
