# Generated by Django 5.0.2 on 2024-03-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_keeperprofile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keeperprofile',
            name='title',
            field=models.CharField(default='Keeper', max_length=255),
        ),
    ]
