# Generated by Django 5.0.3 on 2024-03-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_keeperprofile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='keeperprofile',
            name='instagram_username',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='keeperprofile',
            name='languages',
            field=models.CharField(default='English', help_text='What languages do you speak? (English, Spanish, etc.)', max_length=255),
        ),
        migrations.AddField(
            model_name='keeperprofile',
            name='location',
            field=models.CharField(default='Earth', help_text='Where are you located? (City, State, Country)', max_length=255),
        ),
        migrations.AddField(
            model_name='keeperprofile',
            name='website',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='keeperprofile',
            name='x_username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
