# Generated by Django 5.0.3 on 2024-03-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_keeperprofile_instagram_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keeperprofile',
            name='instagram_username',
            field=models.CharField(help_text='Your Instagram username, no @ symbol', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='keeperprofile',
            name='website',
            field=models.URLField(help_text='Your personal website.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='keeperprofile',
            name='x_username',
            field=models.CharField(help_text='Your X username, no @ symbol', max_length=255, null=True),
        ),
    ]
