# Generated by Django 5.0.3 on 2024-03-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_keeperprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keeperprofile',
            name='instagram_username',
            field=models.CharField(blank=True, default='', help_text='Your Instagram username, no @ symbol', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='keeperprofile',
            name='username',
            field=models.CharField(blank=True, db_index=True, help_text='Your unique username.', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='keeperprofile',
            name='website',
            field=models.URLField(blank=True, default='', help_text='Your personal website.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='keeperprofile',
            name='x_username',
            field=models.CharField(blank=True, default='', help_text='Your X username, no @ symbol', max_length=255),
            preserve_default=False,
        ),
    ]
