# Generated by Django 5.0.3 on 2024-04-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_keeperprofile_instagram_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='newsletter_consent',
            field=models.BooleanField(default=False, verbose_name='I would like to receive updates from Totem.'),
        ),
    ]
