# Generated by Django 5.0.3 on 2024-04-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_user_newsletter_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='newsletter_consent',
            field=models.BooleanField(default=False, verbose_name='Receive updates from Totem'),
        ),
    ]
