# Generated by Django 5.1.7 on 2025-04-21 06:50

import django.db.models.deletion
import totem.users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_user_newsletter_consent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField(default=totem.users.models.default_pin_expires_at)),
                ('used', models.BooleanField(default=False)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
