# Generated by Django 5.1.8 on 2025-04-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_loginpin'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='loginpin',
            index=models.Index(fields=['user', 'pin', 'expires_at'], name='users_login_user_id_f0e42f_idx'),
        ),
    ]
