# Generated by Django 5.1.8 on 2025-05-01 16:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_loginpin_users_login_user_id_f0e42f_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ics_key',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='ICS Key'),
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'token_hash', 'created_at'], name='users_refre_user_id_37e728_idx')],
            },
        ),
    ]
