# Generated by Django 5.1.8 on 2025-05-10 06:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_alter_user_ics_key_refreshtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='API Key'),
        ),
    ]
