# Generated by Django 5.2.4 on 2025-07-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_alter_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fixed_pin',
            field=models.CharField(blank=True, default='', help_text='Fixed PIN for app store review access. Must be enabled to work.', max_length=6, verbose_name='Fixed PIN'),
        ),
        migrations.AddField(
            model_name='user',
            name='fixed_pin_enabled',
            field=models.BooleanField(default=False, help_text='Enable fixed PIN login for app store reviews. Not allowed for staff users.', verbose_name='Fixed PIN Enabled'),
        ),
    ]
