# Generated by Django 5.2.5 on 2025-09-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_user_fixed_pin_user_fixed_pin_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='keeperprofile',
            name='bluesky_username',
            field=models.CharField(blank=True, help_text='Your Bluesky username, no @ symbol', max_length=255),
        ),
    ]
