# Generated by Django 5.2.9 on 2025-12-23 05:37

from django.db import migrations, models


def clear_refresh_tokens(apps, schema_editor):
    """Clear all refresh tokens - switching from Argon2 to SHA-256 hashing."""
    RefreshToken = apps.get_model('users', 'RefreshToken')
    RefreshToken.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_keeperprofile_bluesky_username'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='refreshtoken',
            name='users_refre_user_id_37e728_idx',
        ),
        migrations.RunPython(clear_refresh_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='refreshtoken',
            name='token_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['token_hash', 'is_active'], name='users_refre_token_h_7daf34_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['user', 'created_at'], name='users_refre_user_id_c102a0_idx'),
        ),
    ]
