# Generated by Django 4.1.9 on 2023-05-31 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("onboarded", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("circle_lgbtq", models.BooleanField(default=False)),
                ("circle_mothers", models.BooleanField(default=False)),
                ("circle_sexuality", models.BooleanField(default=False)),
                ("circle_psych", models.BooleanField(default=False)),
                ("circle_general", models.BooleanField(default=False)),
                ("suggestions", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboard",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
