# Generated by Django 4.1.9 on 2023-05-31 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("onboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboardmodel",
            name="internal_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
