# Generated by Django 5.2.9 on 2026-03-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboardmodel",
            name="referral_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("default", "I'm not sure"),
                    ("search", "Search Engine"),
                    ("chatgpt", "ChatGPT"),
                    ("keeper", "A Keeper"),
                    ("social", "Social Media"),
                    ("physical_media", "Physical Media"),
                    ("blog", "Blog or Article"),
                    ("friend", "A friend"),
                    ("other", "Other"),
                    ("pamphlet", "Pamphlet"),
                    ("newsletter", "Newsletter"),
                    ("dream", "✨A Dream✨"),
                ],
                default="default",
                max_length=20,
                verbose_name="How did you hear about us?",
            ),
        ),
    ]
