# Generated by Django 4.1.9 on 2023-06-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("onboard", "0002_onboardmodel_internal_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboardmodel",
            name="timezone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
