# Generated by Django 4.2.5 on 2023-10-09 22:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("onboard", "0005_onboardmodel_hopes_alter_onboardmodel_year_born"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="onboardmodel",
            name="circle_general",
        ),
        migrations.RemoveField(
            model_name="onboardmodel",
            name="circle_lgbtq",
        ),
        migrations.RemoveField(
            model_name="onboardmodel",
            name="circle_mothers",
        ),
        migrations.RemoveField(
            model_name="onboardmodel",
            name="circle_psych",
        ),
        migrations.RemoveField(
            model_name="onboardmodel",
            name="circle_sexuality",
        ),
    ]
