# Generated by Django 5.1.4 on 2025-01-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0007_alter_onboardmodel_hopes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardmodel',
            name='referral_other',
            field=models.CharField(blank=True, help_text='Please tell us more about how you found us', max_length=100, verbose_name='If other, please specify'),
        ),
        migrations.AddField(
            model_name='onboardmodel',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('search', 'Search Results'), ('social', 'Social Media'), ('keeper', 'A Keeper'), ('pamphlet', 'Pamphlet'), ('blog', 'Blog'), ('newsletter', 'Newsletter'), ('dream', 'A Dream')], max_length=20, verbose_name='How did you hear about us?'),
        ),
    ]
