# Generated by Django 5.1.4 on 2025-01-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0008_onboardmodel_referral_other_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardmodel',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('default', "I'm not sure"), ('search', 'Search Results'), ('social', 'Social Media'), ('keeper', 'A Keeper'), ('pamphlet', 'Pamphlet'), ('blog', 'Blog'), ('newsletter', 'Newsletter'), ('dream', '✨A Dream✨'), ('other', 'Other')], max_length=20, verbose_name='How did you hear about us?'),
        ),
    ]
