# Generated by Django 5.2.1 on 2025-05-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0009_alter_onboardmodel_referral_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardmodel',
            name='referral_other',
            field=models.CharField(blank=True, default='', help_text='Please tell us more about how you found us', max_length=100, verbose_name='If other, please specify'),
        ),
        migrations.AlterField(
            model_name='onboardmodel',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('default', "I'm not sure"), ('search', 'Search Results'), ('social', 'Social Media'), ('keeper', 'A Keeper'), ('pamphlet', 'Pamphlet'), ('blog', 'Blog'), ('newsletter', 'Newsletter'), ('dream', '✨A Dream✨'), ('other', 'Other')], default='default', max_length=20, verbose_name='How did you hear about us?'),
        ),
    ]
