# Generated by Django 6.1.1 on 2026-09-08 21:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spaces', '0005_alter_session_duration_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_high', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_high_user', to=settings.AUTH_USER_MODEL)),
                ('user_low', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_low_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=4000)),
                ('client_message_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_for_conversations', to='messaging.message'),
        ),
        migrations.CreateModel(
            name='MessageNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('delivered', 'Delivered'), ('dismissed', 'Dismissed')], default='pending', max_length=12)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='messaging.message')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionMessageRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_request_id', models.UUIDField()),
                ('body', models.CharField(max_length=4000)),
                ('requested_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_message_requests', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_requests', to='spaces.session')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='bulk_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='messaging.sessionmessagerequest'),
        ),
        migrations.CreateModel(
            name='AutomationPrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('kind', models.CharField(choices=[('keeper_follow_up', 'Keeper follow-up'), ('share_upcoming_space', 'Share an upcoming space'), ('participant_discovery', 'Participant discovery')], max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('dismissed', 'Dismissed'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_prompts', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_automation_prompts', to='spaces.session')),
            ],
            options={
                'indexes': [models.Index(fields=['recipient', 'status', '-created_at'], name='messaging_prompt_user_idx'), models.Index(fields=['session', 'kind'], name='messaging_prompt_session_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConversationMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot', models.CharField(choices=[('low', 'Low user'), ('high', 'High user')], max_length=4)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='messaging.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_memberships', to=settings.AUTH_USER_MODEL)),
                ('last_read_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_by_memberships', to='messaging.message')),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-updated_at', '-id'], name='messaging_sync_lookup_idx'), models.Index(fields=['user', 'conversation'], name='messaging_member_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('conversation', 'user'), name='messaging_conversation_member_unique'), models.UniqueConstraint(fields=('conversation', 'slot'), name='messaging_conversation_slot_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-last_activity_at', '-id'], name='messaging_inbox_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(('user_low_id__lt', models.F('user_high_id'))), name='messaging_pair_canonical'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('user_low', 'user_high'), name='messaging_user_pair_unique'),
        ),
        migrations.AddIndex(
            model_name='messagenotification',
            index=models.Index(fields=['status', 'last_attempt_at'], name='messaging_notify_retry_idx'),
        ),
        migrations.AddIndex(
            model_name='messagenotification',
            index=models.Index(fields=['recipient', 'status'], name='messaging_notify_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessionmessagerequest',
            constraint=models.UniqueConstraint(fields=('keeper', 'client_request_id'), name='messaging_keeper_request_unique'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-created_at', '-id'], name='messaging_history_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('client_message_id__isnull', False)), fields=('sender', 'client_message_id'), name='messaging_sender_client_message_unique'),
        ),
    ]
