# Generated by Django 6.1.1 on 2026-09-22 19:53

from django.conf import settings
from django.db import migrations, models


def create_messaging_sync_state(apps, schema_editor):
    apps.get_model("messaging", "MessagingSyncState").objects.get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagingSyncState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('version', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.RunPython(create_messaging_sync_state, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name='conversationmembership',
            name='messaging_sync_lookup_idx',
        ),
        migrations.AddField(
            model_name='conversationmembership',
            name='sync_version',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='conversationmembership',
            index=models.Index(fields=['user', 'sync_version', 'id'], name='messaging_sync_lookup_idx'),
        ),
    ]
