# Generated by Django 5.2.11 on 2026-02-13 23:31

import django.contrib.postgres.fields
import django.db.models.deletion
import totem.rooms.schemas
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spaces', '0003_session_ended_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('waiting_room', 'waiting_room'), ('active', 'active'), ('ended', 'ended')], default=totem.rooms.schemas.RoomStatus['WAITING_ROOM'], max_length=20)),
                ('turn_state', models.CharField(choices=[('idle', 'idle'), ('speaking', 'speaking'), ('passing', 'passing')], default=totem.rooms.schemas.TurnState['IDLE'], max_length=20)),
                ('keeper', models.CharField(max_length=50)),
                ('current_speaker', models.CharField(max_length=50, null=True)),
                ('next_speaker', models.CharField(max_length=50, null=True)),
                ('talking_order', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('state_version', models.PositiveIntegerField(default=0)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='spaces.session')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=50)),
                ('actor', models.CharField(max_length=50)),
                ('snapshot', models.JSONField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='rooms.room')),
            ],
            options={
                'ordering': ['version'],
            },
        ),
    ]
