# Generated by Django 5.2.11 on 2026-02-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='end_reason',
            field=models.CharField(choices=[('keeper_ended', 'keeper_ended'), ('keeper_absent', 'keeper_absent'), ('room_empty', 'room_empty')], default=None, max_length=20, null=True),
        ),
    ]
