# Generated by Django 5.2.11 on 2026-02-24 13:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_end_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='banned_participants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
    ]
