# Generated by Django 6.0.2 on 2026-03-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_banned_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='round_message',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='round_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
