# Generated by Django 6.1.1 on 2026-09-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_round_message_room_round_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='round_message',
        ),
    ]
