# Generated by Django 6.0.8 on 2026-08-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_round_message_room_round_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='turn_started_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
