#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


exec granian --interface wsgi config.wsgi:application \
--host 0.0.0.0 --port $PORT --workers=2 --http 1 --backpressure 20 \
--workers-lifetime 2h --workers-kill-timeout 1m
