# Generated by Django 5.2.9 on 2026-01-13 02:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
import taggit.managers
import totem.spaces.models
import totem.utils.fields
import totem.utils.md
import totem.utils.models
from django.conf import settings
from django.db import migrations, models


# Data migrations from the original migrations are no-ops for fresh installs
# since there's no existing data to migrate.


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=2000)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=totem.utils.models.make_slug, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=2000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False, help_text='Is this listing visible?')),
                ('recurring', models.CharField(help_text='Example: Once a month (or week, day, etc). Do not put specific times or days of the week.', max_length=255)),
                ('author', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='created_spaces', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('open', models.BooleanField(default=True, help_text='Is this listing open for more attendees?')),
                ('content', totem.utils.md.MarkdownField(default='', max_length=10000, validators=[totem.utils.md.MarkdownMixin.validate_markdown, django.core.validators.MaxLengthValidator(10000)])),
                ('subscribed', models.ManyToManyField(blank=True, related_name='subscribed_spaces', to=settings.AUTH_USER_MODEL)),
                ('price', models.IntegerField(default=0, help_text='Price in USD dollars. If you want to offer this listing for free, enter 0.', validators=[django.core.validators.MinValueValidator(0, message='Price must be greater than or equal to 0'), django.core.validators.MaxValueValidator(1000, message='Price must be less than or equal to 1000')], verbose_name='Price (USD)')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Image for the Space header, must be under 5mb', null=True, upload_to=totem.spaces.models.upload_to_id_image)),
                ('categories', models.ManyToManyField(blank=True, to='spaces.spacecategory')),
                ('short_description', models.CharField(blank=True, help_text='Short description, max 255 characters', max_length=255)),
                ('meeting_provider', models.CharField(choices=[('google_meet', 'Google Meet'), ('livekit', 'LiveKit')], default='google_meet', help_text='The video conferencing provider for this space.', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=totem.utils.models.make_slug, editable=False, unique=True)),
                ('open', models.BooleanField(default=True, help_text='Is this session open for more attendees?')),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='Minutes')),
                ('seats', models.IntegerField(default=8)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='sessions_attending', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='spaces.space')),
                ('cancelled', models.BooleanField(default=False, help_text='Is this session canceled?')),
                ('joined', models.ManyToManyField(blank=True, related_name='sessions_joined', to=settings.AUTH_USER_MODEL)),
                ('meeting_url', models.CharField(blank=True, max_length=255)),
                ('advertised', models.BooleanField(default=False)),
                ('notified', models.BooleanField(default=False)),
                ('listed', models.BooleanField(default=True, help_text='Is this session discoverable? False means sessions are only accessible via direct link, or to people attending.')),
                ('notified_tomorrow', models.BooleanField(default=False)),
                ('content', totem.utils.md.MarkdownField(blank=True, help_text='Optional description for this specific session. Markdown is supported.', max_length=10000, null=True, validators=[totem.utils.md.MarkdownMixin.validate_markdown, django.core.validators.MaxLengthValidator(10000)])),
                ('title', models.CharField(blank=True, max_length=255)),
                ('notified_missed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'ordering': ['start'],
                'unique_together': {('space', 'start', 'open', 'title')},
            },
            bases=(totem.utils.md.MarkdownMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SessionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('feedback', models.CharField(choices=[('up', 'Thumbs Up'), ('down', 'Thumbs Down')], max_length=4)),
                ('message', totem.utils.fields.MaxLengthTextField(blank=True, max_length=2000, validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='spaces.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('session', 'user'), name='unique_user_feedback_for_session')],
            },
            bases=(totem.utils.models.AdminURLMixin, models.Model),
        ),
    ]
