# Generated by Django 5.2.9 on 2026-01-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_rename_to_spaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ended_at',
            field=models.DateTimeField(blank=True, help_text='When the session was explicitly ended', null=True),
        ),
    ]
