# Generated by Django 6.0.7 on 2026-08-10 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0004_session_seats_min_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='duration_minutes',
            field=models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Minutes'),
        ),
    ]
