# Generated by Django 6.1.1 on 2026-09-29 18:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_alter_session_duration_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('prompt', models.CharField(max_length=1000)),
                ('position', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('round_number', models.PositiveIntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_prompts', to='spaces.session')),
            ],
            options={
                'verbose_name': 'discussion prompt',
                'verbose_name_plural': 'discussion prompts',
                'ordering': ['position', 'pk'],
            },
        ),
    ]
