# Generated by Django 6.0.7 on 2026-09-28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0005_alter_session_duration_minutes"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionPrompt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("prompt", models.CharField(max_length=1000)),
                ("position", models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="discussion_prompts",
                        to="spaces.session",
                    ),
                ),
            ],
            options={
                "verbose_name": "discussion prompt",
                "verbose_name_plural": "Discussion Prompts",
                "ordering": ["position", "pk"],
            },
        ),
    ]
