# Generated by Django 6.1.1 on 2026-09-30 22:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_alter_session_duration_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('prompt', models.CharField(max_length=1000)),
                ('position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_prompts', to='spaces.session')),
            ],
            options={
                'verbose_name': 'discussion prompt',
                'verbose_name_plural': 'discussion prompts',
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='prompts_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SessionRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
                ('prompt', models.CharField(blank=True, max_length=2000)),
                ('state', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('prepared_prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_rounds', to='spaces.sessionprompt')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='spaces.session')),
            ],
            options={
                'ordering': ['number'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('session', 'number'), name='unique_session_round_number')],
            },
        ),
    ]
