# Generated by Django 6.0.7 on 2026-09-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0006_sessionprompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="current_prompt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="spaces.sessionprompt",
            ),
        ),
    ]
